### PR TITLE
Backport rmw callbacks implementation to Humble [ros2-73]

### LINKED ISSUE #155: :farmer: rclcpp tests failing due to rmw callbacks not implemented in Humble ci and Iron ci
- Ubuntu jammy and noble
- Humble and Iron source

**How to Reproduce**
1. Run a build in Hci_nightly_connext or Ici_nightly_connext
2. See tests failures

**Bug Description**

Reference builds:
* [Humble#254](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/) (already fixed)
* [Iron#167](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/#showFailuresLink)

Failing test (updated):

`rmw_client_set_on_new_response_callback not implemented`:
* [projectroot.test.rclcpp.test_client](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/testReport/junit/projectroot.test/rclcpp/test_client/)

`rmw_service_set_on_new_request_callback not implemented`:
* [projectroot.test.rclcpp.test_service](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/testReport/junit/projectroot.test/rclcpp/test_service/)
* [rclcpp.TestService.on_new_request_callback](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/testReport/junit/rclcpp/TestService/on_new_request_callback/)

`rmw_subscription_set_on_new_message_callback`:
* [projectroot.test.rclcpp.test_subscription](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/testReport/junit/projectroot.test/rclcpp/test_subscription/)
* [rclcpp.TestSubscription.on_new_message_callback](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/testReport/junit/rclcpp/TestSubscription/on_new_message_callback/)\
* [projectroot.test.rclcpp.test_executors](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/testReport/junit/projectroot.test/rclcpp/test_executors/)
* [rclcpp.TestIntraprocessExecutors/EventsExecutor.testIntraprocessRetrigger](https://build.ros2.org/view/Ici/job/Ici__nightly-connext_ubuntu_jammy_amd64/167/testReport/junit/rclcpp/TestIntraprocessExecutors_EventsExecutor/testIntraprocessRetrigger/)

<details>
<summary>
Failing tests (before 17-09-2023):
</summary>

`rmw_client_set_on_new_response_callback not implemented`:
* [projectroot.test.rclcpp.test_client](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/projectroot.test/rclcpp/test_client/)
* [rclcpp.TestClient.on_new_response_callback](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/rclcpp/TestClient/on_new_response_callback/)

`rmw_event_set_callback not implemented` (Hci only):
* [projectroot.test.rclcpp.test_qos_event](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/projectroot.test/rclcpp/test_qos_event/)
* [rclcpp.TestQosEvent.test_on_new_event_callback](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/rclcpp/TestQosEvent/test_on_new_event_callback/)
* [rclcpp.TestQosEvent.test_invalid_on_new_event_callback](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/rclcpp/TestQosEvent/test_invalid_on_new_event_callback/)

`rmw_service_set_on_new_request_callback not implemented`:
* [projectroot.test.rclcpp.test_service](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/projectroot.test/rclcpp/test_service/)
* [rclcpp.TestService.on_new_request_callback](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/rclcpp/TestService/on_new_request_callback/)

`rmw_subscription_set_on_new_message_callback`:
* [projectroot.test.rclcpp.test_subscription](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/projectroot.test/rclcpp/test_subscription/)
* [rclcpp.TestSubscription.on_new_message_callback](https://build.ros2.org/job/Hci__nightly-connext_ubuntu_jammy_amd64/254/testReport/junit/rclcpp/TestSubscription/on_new_message_callback/)
* [projectroot.test.rclcpp.test_executors](https://build.ros2.org/job/Ici__nightly-connext_ubuntu_jammy_amd64/149/testReport/junit/projectroot.test/rclcpp/test_executors/) (Ici only)
* [rclcpp.TestIntraprocessExecutors/EventsExecutor.testIntraprocessRetrigger](https://build.ros2.org/job/Ici__nightly-connext_ubuntu_jammy_amd64/149/testReport/junit/rclcpp/TestIntraprocessExecutors_EventsExecutor/testIntraprocessRetrigger/) (Ici only)
 > **Note**: rmw_api_connextdds_subscription_get_network_flow_endpoints: not implemented is also showing here

</details>

Full log output:

```
unknown file: Failure
C++ exception with description "failed to set the on new response callback for client: rmw_client_set_on_new_response_callback not implemented, at /tmp/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_listener.cpp:58" thrown in the test body.

...

unknown file: Failure
C++ exception with description "failed to set the on new message callback for QOS Event: rmw_event_set_callback not implemented, at /tmp/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_listener.cpp:29" thrown in the test body.

...

unknown file: Failure
C++ exception with description "failed to set the on new request callback for service: rmw_service_set_on_new_request_callback not implemented, at /tmp/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_listener.cpp:45" thrown in the test body.

...

unknown file: Failure
C++ exception with description "failed to set the on new message callback for subscription: rmw_subscription_set_on_new_message_callback not implemented, at /tmp/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_listener.cpp:74" thrown in the test body.
```

### PR DESCRIPTION
**Pull request by trubio-rti**
This fixes #155. I've also sneakily backported the fix to allow Humble to build with Connext 7.3.0.

`ci_linux`: [Build Status](https://ci.ros2.org/job/ci_linux/)
`ci_linux_rhel`: [Build Status](https://ci.ros2.org/job/ci_linux-rhel/)
`ci_windows`: [Build Status](https://ci.ros2.org/job/ci_windows/)

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
In general, this looks good to me when CI is green.

For running the CI, you'll need to do some slightly different things.  In particular, you should use https://ci.ros2.org/job/ci_launcher/, which will output a snippet for you to paste into this PR.   You will also need to make sure to run it with the correct arguments; in this case, it will have to be a ros2.repos file from Humble (with this PR in place for rmw_connextdds), you'll need to select "humble" as the ROS_DISTRO, you'll need to set the UBUNTU_DISTRO to jammy, and you'll need to set the RHEL_DISTRO to 8.

**Comment by trubio-rti** [comment]
This fix should be enough I think. I don't think the Qt failures on Windows are related to this project. Could you confirm it, please?

Linux [Build Status](https://ci.ros2.org/job/ci_linux/)
Windows [Build Status](https://ci.ros2.org/job/ci_windows/22342/)

**Comment by clalancette** [comment]
> This fix should be enough I think. I don't think the Qt failures on Windows are related to this project. Could you confirm it, please?

Yeah, those Qt failures are separate.

File: rmw_connextdds_common/include/rmw_connextdds/rmw_waitset_std.hpp [hunk 1]
```diff
@@ -333,8 +350,55 @@ class RMW_Connext_StatusCondition : public RMW_Connext_Condition
...
 protected:
   DDS_StatusCondition * scond;
+  std::mutex new_event_mutex_;
+  rmw_event_callback_t new_event_cb_[RMW_EVENT_INVALID] = {};
+  const void * user_data_[RMW_EVENT_INVALID] = {};
+  uint64_t unread_events_count_[RMW_EVENT_INVALID] = {0};
+
+  bool triggered_inconsistent_topic{false};
+
+  struct DDS_InconsistentTopicStatus status_inconsistent_topic;
```
Comment (fujitatomoya) [inline rmw_connextdds_common/include/rmw_connextdds/rmw_waitset_std.hpp:401]: There changes obviously break the ABI compatibility, are we allowed to do that in this particular time?

Comment (clalancette) [reply rmw_connextdds_common/include/rmw_connextdds/rmw_waitset_std.hpp:401]: > There changes obviously break the ABI compatibility, are we allowed to do that in this particular time?

It's true that this breaks ABI.  In this case, I approved it anyway because the ABI is between `rmw_connextdds_common` and `rmw_connextdds`; it seems doubtful someone is relying on that.  Also, for some other RMWs we have broken ABI in this way before if it was "internal" to the RMW.

But it is a conversation worth having; should we allow this kind of ABI breakage in stable distributions?

Comment (fujitatomoya) [reply rmw_connextdds_common/include/rmw_connextdds/rmw_waitset_std.hpp:401]: i think that is okay in this case to break the ABI, i do not expect there could be someone relying on rmw implementation APIs...

> But it is a conversation worth having; should we allow this kind of ABI breakage in stable distributions?

IMO, i think rmw implementation can break the internal ABI in stable distributions. as long as RMW interface is compatible, there should be no problem? agree that this is worth to bring up for the discussion.

Comment (trubio-rti) [reply rmw_connextdds_common/include/rmw_connextdds/rmw_waitset_std.hpp:401]: Would you be ok with this change then? I prefer to be sure than to revert.

As I see it, this would only break compatibility from programs that directly call the Connext RMW API, which would be defeating the purpose of the RMW in the first place. The ABI of the `rmw_connextdds` and `rmw` packages is still stable, so it shouldn't be an issue.

Comment (clalancette) [reply rmw_connextdds_common/include/rmw_connextdds/rmw_waitset_std.hpp:401]: > Would you be ok with this change then? I prefer to be sure than to revert.

Let's hold off until next week; we'll have a discussion in the ROS PMC meeting about it.

**Comment by MichaelOrlov** [comment]
@mjcarroll Friendly ping in this issue. We decided to merge it.

**Comment by Blast545** [comment]
:man_farmer: Thanks for pushing this one @trubio-rti, can this also be backported to Iron?

**Comment by Blast545** [comment]
friendly ping @trubio-rti @fgallegosalido

**Comment by fgallegosalido** [comment]
Hi @Blast545. As Iron's EoL is close (shy of a month), we think it's not worthy investing resources into it. Is it really necessary to backport this issue to Iron?

**Comment by claraberendsen** [comment]
@fgallegosalido I brought this subject up on the ROS PMC meeting and the decision was to not make the forward port on this for Iron. I will close the related issue since it has been solved for Humble. Thanks for the work here !
