### PR TITLE
fix security certificate error message format.

### LINKED ISSUE #170: 🧑‍🌾 Rolling CI warning: `format ‘%s’ expects a matching ‘char*’ `
**System Info**

- _OS_
  - Ubuntu 20.04
- *ROS version and installation type*
  - Rolling
- *RTI Connext DDS version and installation type*
  - CI Install

**Bug Description**

Reference builds:
- https://ci.ros2.org/job/nightly_linux_repeated/3746/gcc/
- https://ci.ros2.org/job/nightly_linux_coverage/2690/gcc/
- https://build.ros2.org/job/Rci__nightly-release_ubuntu_noble_amd64/302/gcc/
- https://build.ros2.org/job/Rci__nightly-debug_ubuntu_noble_amd64/300/gcc/
- https://build.ros2.org/job/Rci__nightly-connext_ubuntu_noble_amd64/309/gcc/new/

Warning:
- [rmw_context.cpp:473](https://ci.ros2.org/job/nightly_linux_repeated/3746/gcc/source.3af33c60-fb21-4440-a5c0-b9a8460f5580/#473): `format ‘%s’ expects a matching ‘char*’ argument [-Wformat=] 473 | "failed to assert DDS property: '%s' = '%s'",`

```
In file included from /home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/include/rmw_connextdds/log.hpp:20,
                 from /home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/include/rmw_connextdds/context.hpp:24,
                 from /home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/include/rmw_connextdds/rmw_impl.hpp:25,
                 from /home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp:26:
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp: In member function ‘rmw_ret_t rmw_context_impl_s::configure_security(DDS_DomainParticipantQos*)’:
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp:473:7: warning: format ‘%s’ expects a matching ‘char*’ argument [-Wformat=]
  473 |       "failed to assert DDS property: '%s' = '%s'",
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/include/rmw_connextdds/log.hpp:195:3: note: in expansion of macro ‘RMW_CONNEXT_LOG_ERROR_A’
  195 |   RMW_CONNEXT_LOG_ERROR_A(fmt_, __VA_ARGS__) \
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp:472:5: note: in expansion of macro ‘RMW_CONNEXT_LOG_ERROR_A_SET’
  472 |     RMW_CONNEXT_LOG_ERROR_A_SET(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jenkins-agent/workspace/nightly_linux_repeated/ws/install/rmw/include/rmw/rmw/error_handling.h:31,
                 from /home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp:24:
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp:473:7: warning: format ‘%s’ expects a matching ‘char*’ argument [-Wformat=]
  473 |       "failed to assert DDS property: '%s' = '%s'",
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp:472:5: note: in expansion of macro ‘RMW_CONNEXT_LOG_ERROR_A_SET’
  472 |     RMW_CONNEXT_LOG_ERROR_A_SET(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jenkins-agent/workspace/nightly_linux_repeated/ws/src/ros2/rmw_connextdds/rmw_connextdds_common/src/common/rmw_context.cpp:473:48: note: format string is defined here
  473 |       "failed to assert DDS property: '%s' = '%s'",
      |                                               ~^
      |                                                |
      |                                                char*
```

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/rmw_connextdds/issues/170

missing string value for the format.

introduced by https://github.com/ros2/rmw_connextdds/pull/167.

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@ahcorde can you take a look and merge?

i am not sure why this is not detected by CI with https://github.com/ros2/rmw_connextdds/pull/167.

**Comment by fujitatomoya** [comment]
Pulls: ros2/rmw_connextdds#171
Gist: https://gist.githubusercontent.com/fujitatomoya/a1bd0be9a7cd11147b341aa5aaa199f9/raw/eade078da70a6fb9f26c4f57cbc36e977447a31b/ros2.repos
BUILD args:  --packages-above-and-dependencies rmw_connextdds_common
TEST args:  --packages-above rmw_connextdds_common
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/15247
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22592/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16835/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2111/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23397/)

**Review by ahcorde — APPROVED** [review]

File: rmw_connextdds_common/src/common/rmw_context.cpp [hunk 1]
```diff
@@ -471,6 +471,7 @@ rmw_context_impl_s::configure_security(DDS_DomainParticipantQos * const qos)
   {
     RMW_CONNEXT_LOG_ERROR_A_SET(
       "failed to assert DDS property: '%s' = '%s'",
+      DDS_SECURITY_IDENTITY_CERTIFICATE_PROPERTY,
```
Comment (christophebedard) [inline rmw_connextdds_common/src/common/rmw_context.cpp]: Shouldn't this be `DDS_SECURITY_PRIVATE_KEY_PROPERTY`?

Comment (fujitatomoya) [reply rmw_connextdds_common/src/common/rmw_context.cpp]: Ah right, i picked up from wrong line.

**Comment by fujitatomoya** [comment]
CI:
Building on the built-in node in workspace /var/lib/jenkins/workspace/ci_launcher
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22595/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16838/) (supposed to fail)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/2114/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/23400/)

**Review by christophebedard — APPROVED** [review]

**Comment by ahcorde** [comment]
Windows warnings are unrelated. Merging
